
//! Autogenerated weights for `peaq_pallet_mor`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2024-09-23, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ip-99-1-200-206`, CPU: `AMD EPYC 7R32`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev-local")`, DB CACHE: 1024

// Executed Command:
// ./target/release/peaq-node
// benchmark
// pallet
// --chain=dev-local
// --execution=native
// --wasm-execution=compiled
// --pallet=peaq-pallet-mor
// --extrinsic=*
// --steps=50
// --repeat=20
// --output=weight.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `peaq_pallet_mor`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::WeightInfo for WeightInfo<T> {
	/// Storage: `PeaqDid::OwnerStore` (r:1 w:0)
	/// Proof: `PeaqDid::OwnerStore` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `PeaqMor::MachineRegister` (r:1 w:1)
	/// Proof: `PeaqMor::MachineRegister` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `PeaqMor::MorConfigStorage` (r:1 w:0)
	/// Proof: `PeaqMor::MorConfigStorage` (`max_values`: Some(1), `max_size`: Some(49), added: 544, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn get_registration_reward() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `531`
		//  Estimated: `3593`
		// Minimum execution time: 59_822_000 picoseconds.
		Weight::from_parts(60_571_000, 0)
			.saturating_add(Weight::from_parts(0, 3593))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `PeaqDid::OwnerStore` (r:1 w:0)
	/// Proof: `PeaqDid::OwnerStore` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `PeaqMor::MachineRegister` (r:1 w:0)
	/// Proof: `PeaqMor::MachineRegister` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `PeaqMor::PeriodRewardStorage` (r:1 w:0)
	/// Proof: `PeaqMor::PeriodRewardStorage` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn get_online_rewards() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `609`
		//  Estimated: `3593`
		// Minimum execution time: 35_011_000 picoseconds.
		Weight::from_parts(35_521_000, 0)
			.saturating_add(Weight::from_parts(0, 3593))
			.saturating_add(T::DbWeight::get().reads(4))
	}
	/// Storage: `PeaqMor::MorConfigStorage` (r:1 w:0)
	/// Proof: `PeaqMor::MorConfigStorage` (`max_values`: Some(1), `max_size`: Some(49), added: 544, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn pay_machine_usage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `198`
		//  Estimated: `3593`
		// Minimum execution time: 43_981_000 picoseconds.
		Weight::from_parts(44_691_000, 0)
			.saturating_add(Weight::from_parts(0, 3593))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `PeaqMor::RewardsRecordStorage` (r:1 w:1)
	/// Proof: `PeaqMor::RewardsRecordStorage` (`max_values`: Some(1), `max_size`: Some(4083), added: 4578, mode: `MaxEncodedLen`)
	/// Storage: `PeaqMor::MorConfigStorage` (r:0 w:1)
	/// Proof: `PeaqMor::MorConfigStorage` (`max_values`: Some(1), `max_size`: Some(49), added: 544, mode: `MaxEncodedLen`)
	fn set_configuration() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3377`
		//  Estimated: `5568`
		// Minimum execution time: 18_730_000 picoseconds.
		Weight::from_parts(19_080_000, 0)
			.saturating_add(Weight::from_parts(0, 5568))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn fetch_pot_balance() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `39`
		//  Estimated: `3593`
		// Minimum execution time: 12_150_000 picoseconds.
		Weight::from_parts(12_390_000, 0)
			.saturating_add(Weight::from_parts(0, 3593))
			.saturating_add(T::DbWeight::get().reads(1))
	}
}
